### ISSUE TITLE
Can't send to `AsyncChannel` in the same context it was created

### ISSUE THREAD

**Issue by lmcd** [apple/swift-async-algorithms#308] opened 2024-03-10 03:33 UTC
Task {
        let channel1 = AsyncChannel<Int>()
        await channel1.send(0)
        Swift.print("Sent")
    }

This never prints anything. Is this a bug?

This doesn't appear to be a problem with deallocation. Even if I set the channel to a property of a retained object, it still doesn't work.

**Comment by kperryua** [comment] 2024-03-10 04:41
This is by design. One main purpose of AsyncChannel is to exert backpressure on the sender.

As noted in the guide: [here](https://github.com/apple/swift-async-algorithms/blob/main/Sources/AsyncAlgorithms/AsyncAlgorithms.docc/Guides/Channel.md)

> That awaiting behavior will allow for the affordance of back pressure applied from the consumption site to be transmitted to the production site. This means that the rate of production cannot exceed the rate of consumption, and that the rate of consumption cannot exceed the rate of production.

If another task was to consume the value you’ve sent, the print statement would execute.

**Comment by FranzBusch** [comment] 2024-04-04 08:45
Closing this issue since this works as designed.

**Closed by FranzBusch** 2024-04-04 08:45 UTC
