### ISSUE TITLE
Type erasure of AsyncSequences

### ISSUE THREAD

**Issue by BrentMifsud** [apple/swift-async-algorithms#279] opened 2023-07-24 20:29 UTC
I have been using this package quite a bit recently and one of the biggest pain points for me is how verbose the type inference tends to get when you start stringing these AsyncSequences together.

Similar to combine's `AnyPublisher<Element,Failure>` I believe that this package should expose a way to easily erase the type of the async sequence that is being produced.

Whether that be through a new `AnyAsyncSequence` type or leveraging the existing `AsyncStream` and `AsyncThrowingStream` types.

I realize that today `AsyncSequence` cannot expose its failure type (or lack thereof) and that is probably the reason why something like this does not exist today.

But maybe as a pre 1.x.x convenience we could add something that solves this issue.

At my current company (and in my own personal projects) I use something like this:

```swift
fileprivate extension AsyncStream {
    init<Base: AsyncSequence>(from sequence: Base, file: StaticString = #filePath, line: UInt = #line) where Element == Base.Element {
        var iterator = sequence.makeAsyncIterator()
        // FIXME: In later swift versions, AsyncSequence protocol will likely have an associated error type.
        // FIXME: For now, produce an assertionFailure to let developer know to use an AsyncThrowingStream instead.
        self.init {
            do {
                return try await iterator.next()
            } catch {
                assertionFailure("AsyncSequence threw \(error.localizedDescription). Use AsyncThrowingStream instead", file: file, line: line)
                return nil
            }
        }
    }
}

fileprivate extension AsyncThrowingStream {
    init<Base: AsyncSequence>(from sequence: Base) where Element == Base.Element, Failure == Error {
        var iterator = sequence.makeAsyncIterator()
        self.init {
            try await iterator.next()
        }
    }
}

extension AsyncSequence {
    /// Type erases the `AsyncSequence` into an `AsyncStream`
    /// - Returns: An `AsyncStream` created from the base `AsyncSequence`
    ///
    /// - Note: AsyncSequences do not expose their error type.
    /// So this function is available for both throwing and non-throwing `AsyncSequences`.
    /// It will produce an `assertionFailure` at runtime if the base sequence throws.
    func asAsyncStream(file: StaticString = #filePath, line: UInt = #line) -> AsyncStream<Element> {
        AsyncStream(from: self, file: file, line: line)
    }

    /// Type erases the `AsyncSequence` into an `AsyncThrowingStream`
    /// - Returns: An `AsyncThrowingStream` from the base `AsyncSequence`
    func asAsyncThrowingStream() -> AsyncThrowingStream<Element, Error> {
        AsyncThrowingStream(from: self)
    }
}
```

**Comment by tcldr** [comment] 2023-07-25 08:04
Hi @BrentMifsud – you may have better engagement if you post on the [Swift forums](https://forums.swift.org/c/related-projects/swift-async-algorithms/86). This definitely feels like an issue that is due further and wider discussion.

**Comment by FranzBusch** [comment] 2023-07-25 09:48
@BrentMifsud We know that this is a usability issue right now but it is not something that we want to fix with introducing an `AnyAsyncSequence`. We really want to express this using `any` and `some` but this requires two things:

1. Adopting primary associated types on `AsyncSequence`.
2. Being able to express something like `some throwing AsyncSequence<Int>`

Both of those require language work and I think we should focus our discussions around how to solve those two issues. This would indeed be something for the forums.

**Comment by jshier** [comment] 2023-07-25 15:42
Not wanting to introduce `AnyAsyncSequence` to the standard library is perfectly understandable. Not wanting to introduce it to an external library is less so. What exactly are the downsides to this library filling a critical hole?

**Comment by FranzBusch** [comment] 2023-07-25 16:36
> What exactly are the downsides to this library filling a critical hole?

The problem is that I don't think we can express what we want here really unless we make `AnyAsyncSequence` always throwing. Which to me sounds like a severe limitation. I also don't see it pressing for async-algos to fill this gap which sets out to implement generic algorithms on top of async sequences. `AnyAsyncSequence` is really more of a tool for internal API design and can be solved in the respective applications. For public API we recommend to create a concrete named type anyhow instead of resorting to `AnyAsyncSequence`.

**Comment by BrentMifsud** [comment] 2023-08-03 03:38
I tend to agree with most of the comments here about this being something that should be done as part of the swift language. Rather than in this package.

I'll bring this discussion over to the swift forums.

**Comment by FranzBusch** [comment] 2023-09-21 08:16
Since this requires language work and there is an active thread in the forums. I will close this issue. Let's continue the discussion in the forums.

**Closed by FranzBusch** 2023-09-21 08:16 UTC
