### ISSUE TITLE
Xcode 14 (14A309) regression: Project does not build

### ISSUE THREAD

**Issue by Sajjon** [apple/swift-async-algorithms#199] opened 2022-09-13 08:35 UTC
I just downloaded Xcode 14 (non beta), version 14A309, and this project fails to compile.

<img width="1804" alt="Screenshot 2022-09-13 at 10 34 29" src="https://user-images.githubusercontent.com/864410/189853402-ef8591ae-66fe-4522-a5a2-eaf134c17ba7.png">

**Comment by stephentyrone** [comment] 2022-09-13 13:11
I put a note on your forums post, but this is a consequence of Xcode 14 containing a macOS 12 SDK, which has the Swift 5.6 standard library. For development using Swift 5.7 features targeting macOS, you should continue using the Xcode beta until a release with the macOS 13 SDK is available.

**Comment by minacle** [comment] 2022-09-13 13:40
Duplicate of #195

**Comment by Sajjon** [comment] 2022-09-13 13:41
@stephentyrone @phausler  What will be the minimum deployment target for an iOS app using this library?

Because the Package.swift states:

```swift
  platforms: [
    .macOS("10.15"),
    .iOS("13.0"),
    .tvOS("13.0"),
    .watchOS("6.0")
  ],
```

[But Apple Documentation of `Clock` states iOS 16](https://developer.apple.com/documentation/swift/clock?changes=_3)

And this discrepancy, iOS 13 vs iOS 16 confuses me, ought to be the same, and which is that? iOS 16? 

Thus I cannot ship any iOS app which needs to target iOS 13, if this package in fact requires iOS 16?

**Comment by FranzBusch** [comment] 2022-09-13 13:44
This project should still require iOS 13 to build and all the algorithm that require `Clock` are guarded with `@availability` checks. In practice, this means that all algorithms that are using `Clock` are only useable from iOS 16 onwards.

**Comment by Sajjon** [comment] 2022-09-13 13:47
So @FranzBusch TL;DR is: I can ship an app using this project, targeting iOS 13. But for iOS 16 users, under the hood, their version of the app will using `Clock`, which does not really lead to any changed behaviour..? Apart from being a Developer Experience upgrade? (I dont know if `Clock` etc will give any performace upgrade?)

**Comment by FranzBusch** [comment] 2022-09-13 13:49
> So @FranzBusch TL;DR is: I can ship an app using this project, targeting iOS 13. But for iOS 16 users, under the hood, their version of the app will using `Clock`, which does not really lead to any changed behaviour..? Apart from being a Developer Experience upgrade? (I dont know if `Clock` etc will give any performace upgrade?)

That is not quite right. You can ship an app using this package targeting iOS 13; however, you cannot use operators like `debounce` since the `Clock` API is not present in the SDKs before iOS 16. As long as you stick to operators that are not using `Clock` based implementations you won't face any problems.

**Comment by Sajjon** [comment] 2022-09-13 13:51
@FranzBusch Right, makes perfect sense, thank you so much!

**Closed** 2023-02-10 21:30 UTC
