### ISSUE TITLE
Debounce silently swallows thrown errors and stalls iteration

### ISSUE THREAD

**Issue by pocketpixels** [apple/swift-async-algorithms#269] opened 2023-06-13 21:23 UTC
I discovered while debugging an issue in my app that the async sequence returned by `AsyncThrowingStream.debounce()` silently swallows thrown exceptions, and does not terminate, instead just stalling iteration. 

```swift
struct MyError: Error {}

let (stream, continuation) = AsyncThrowingStream.makeStream(of: Int.self)

// consume the stream
Task {
    do {
        for try await value in stream.debounce(for: .seconds(0.1)) {
            print(value)
        }
        print("Stream ended normally")
    }
    catch {
        print("Stream ended by throwing")
    }
}

// produce the values (and exception)
Task {
    for i in 1...10 {
        if i == 5 {
            continuation.finish(throwing: MyError())
        }
        else {
            continuation.yield(i)
        }
        try await Task.sleep(for: .seconds(0.3))
    }
    continuation.finish()
}
```

Running this in a playground (see attached project below), the iteration prints 1, 2, 3, 4 and then just stalls. 
Removing the `debounce`, iteration ends by throwing as expected. 

[DebounceDebug.zip](https://github.com/apple/swift-async-algorithms/files/11739430/DebounceDebug.zip)

**Comment by FranzBusch** [comment] 2023-08-24 15:15
Just coming back to and I just wrote a test for this to see if I can reproduce it.

```
func test() async throws {
    struct MyError: Error {}

    let (stream, continuation) = AsyncThrowingStream.makeStream(of: Int.self)

    try await withThrowingTaskGroup(of: Void.self) { group in
        group.addTask {
            for i in 1...10 {
                if i == 5 {
                    continuation.finish(throwing: MyError())
                }
                else {
                    continuation.yield(i)
                }
                try await Task.sleep(for: .seconds(0.03))
            }
            continuation.finish()
        }

        do {
            for try await value in stream.debounce(for: .seconds(0.01)) {
                print(value)
            }
            print("Stream ended normally")
        }
        catch {
            print("Stream ended by throwing")
        }

    }
}
```

I wasn't able to reproduce it with this. Your attached project also doesn't contain the playground so I couldn't look at your code. Could you provide more information here?

**Comment by pocketpixels** [comment] 2023-08-24 20:58
Sorry for the missing playground file. 
Please try this fixed version:
[DebounceDebug.zip](https://github.com/apple/swift-async-algorithms/files/12433233/DebounceDebug.zip)

Your code is different from my playground code in that you are using a TaskGroup and yielding or throwing everything simultaneously instead of sequentially. 

Try the Playground in the attached project. I can still reproduce the behaviour with it in the latest Xcode beta.

**Comment by FranzBusch** [comment] 2023-08-25 09:32
I can reproduce it in the playground but I am a bit skeptical of the playground environment here. I wasn't able to repro this in a test case even with just using your code. Are you able to reproduce this in a non-playground environment?

**Comment by pocketpixels** [comment] 2023-08-25 21:09
I did encounter this issue in production code and fixed it by removing the `debounce` and using a different approach. 

I just hacked it into the ContentView template code, and can reproduce the issue both in the Simulator and on device. 

[DebounceDebug.zip](https://github.com/apple/swift-async-algorithms/files/12443522/DebounceDebug.zip)

**Comment by FranzBusch** [comment] 2023-08-25 21:24
Ah I think I know what the problem is and why I wasn't able to reproduce it. This was a change in behaviour in 5.8 for `group.waitForAll` which I have fixed in this PR: https://github.com/apple/swift-async-algorithms/pull/254.

We haven't done a release since but could you try to depend on `main` instead of the `0.1.0` tag and test it again?

**Comment by pocketpixels** [comment] 2023-08-25 21:34
I just tried that and can confirm that switching to `main` fixes this issue.

**Comment by FranzBusch** [comment] 2023-08-25 21:37
Thanks so much!

**Closed** 2023-08-25 21:37 UTC
